language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install nose pylint
  - pip install docker
# command to run tests
script:
  - find . -name "*.py" | grep -v git_pull_codedir.py | xargs pylint -E
