language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install nose pylint
  - pip install docker
  # https://codeinthehole.com/tips/using-pip-and-requirementstxt-to-install-from-the-head-of-a-github-branch/
  - pip install git+git://github.com/tangentlabs/django-oscar.git#egg=django-oscar
# command to run tests
script:
  - find . -name "*.py" | xargs pylint -E
